linters:
  enable:
    - goheader
    - revive
    - unused
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 20[0-9][0-9]
    template-path: code-header-template.txt
  revive:
    enable-all-rules: true
    rules:
    - name: add-constant
      disabled: true
    - name: cognitive-complexity
      disabled: true
    - name: cyclomatic
      disabled: true
    - name: confusing-naming
      disabled: true
    - name: confusing-results
      disabled: true
    - name: dot-imports
      disabled: true
    - name: early-return
      disabled: true
    - name: empty-lines
      disabled: true
    - name: flag-parameter
      disabled: true
    - name: function-length
      disabled: true
    - name: function-result-limit
      disabled: true
    - name: import-shadowing
      disabled: true
    - name: line-length-limit
      disabled: true
    - name: max-public-structs
      disabled: true
    - name: modifies-value-receiver
      disabled: true
    - name: redefines-builtin-id
      disabled: true
    - name: unchecked-type-assertion
      disabled: true
    - name: unnecessary-stmt
      disabled: true
    - name: unused-receiver
      disabled: true
    - name: use-any
      disabled: true
    - name: use-errors-new
      disabled: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-dirs:
    - pkg/yamlmeta/internal
  new-from-rev: bd77aced0a1cd6d6f3ecd3ed04c1832e1c513ab0
