linters:
  enable:
    - goheader
    - golint
    - deadcode
    - unused
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 202[0-1]
    template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  skip-dirs:
    - pkg/yamlmeta/internal
