linters:
  enable:
    - goheader
    - revive
    - unused
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 20[0-9][0-9]
    template-path: code-header-template.txt
  revive:
    enable-all-rules: true
    rules:
    - name: dot-imports
      disabled: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-dirs:
    - pkg/yamlmeta/internal
  new-from-rev: 960a70d2f690a9c1fffa7f7a8a398c1b8de04a61
