#@ load("@ytt:overlay", "overlay")
#@data/values
---
keys:
  #@overlay/remove
  key1:
  key2: val2-new
  #@overlay/match missing_ok=True
  key3: val3
names:
#@overlay/match by=overlay.subset("default.example.com")
#@overlay/remove
-
#@overlay/append
- production.example.com
