#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ def/end test1_left():
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress1
  annotations:
    key: 1

#@ def/end test1_right():
#@overlay/match by=overlay.all
---
metadata:
  annotations:
    key: 2

---
test1
--- #@ template.replace(overlay.apply(test1_left(), test1_right()))
---
+++

OUTPUT POSITION:          stdin:20 | [doc]
                   |   test1
           stdin:5 | [doc]
           stdin:6 |   apiVersion: extensions/v1beta1
           stdin:7 |   kind: Ingress
           stdin:8 |   metadata:
           stdin:9 |     name: example-ingress1
          stdin:10 |     annotations:
          stdin:18 |       key: 2
