#! to stop templating and throw a custom error message
#! use the fail() function from ytt's assert module

#@ load("@ytt:assert", "assert")

#@ val = 123

key: #@ val if val > 150 else assert.fail("val is too small")
