#@ load("@ytt:data", "data")

#! data.list() provides a list of all files given to ytt
#! (which also includes template files themselves)

#! to load the raw content from a file as a string,
#! i.e. without applying any templating, use data.read(...)

#@ files = data.list()

files: #@ files

csvs:
#@ for/end file in [ f for f in files if f.endswith(".csv") ]:
- #@ data.read(file)
