---
name: Add issues to project

on:
  issues:
    types: ['opened']
  pull_request_target:
    types: ['opened']

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/carvel-dev/projects/1
          github-token: ${{ secrets.CARVEL_ADD_TO_PROJECT_TOKEN }}
